export const list = [
    {
        nombre: 'Remera Oversize Bluished',
        tipo: 'remera',
        genero: 'hombre',
        talle: 's',
        precio: 1000,
    },
    {
        nombre: 'Remera Oversize Dunk',
        tipo: 'remera',
        genero: 'hombre',
        talle: 'm',
        precio: 3000,
    },
    {
        nombre: 'Remera Oversize Nike',
        tipo: 'remera',
        genero: 'hombre',
        talle: 'l',
        precio: 12000,
    },
    {
        nombre: 'Remera Oversize Adidas',
        tipo: 'remera',
        genero: 'mujer',
        talle: 's',
        precio: 1000,
    },
    {
        nombre: 'Abrigo Oversize Bluished',
        tipo: 'abrigo',
        genero: 'hombre',
        talle: 's',
        precio: 1000,
    },
    {
        nombre: 'Remera Oversize Piola',
        tipo: 'remera',
        genero: 'hombre',
        talle: 'l',
        precio: 1000,
    },
    {
        nombre: 'Remera Slim Bluished',
        tipo: 'remera',
        genero: 'mujer',
        talle: 's',
        precio: 1000,
    },
    {
        nombre: 'Remera Oversize Bluished',
        tipo: 'remera',
        genero: 'mujer',
        talle: 'l',
        precio: 1000,
    },
    {
        nombre: 'Abrigo Oversize Bluished',
        tipo: 'abrigo',
        genero: 'mujer',
        talle: 'm',
        precio: 1000,
    },
]